import type { AttemptReceipt, Comment, IssuedChallenge, NetworkState, Post, Progress, Activity, LeaderRow } from './types'
import type { TransmissionRule } from './transmission'
const record = (v: unknown): v is Record<string, unknown> => !!v && typeof v === 'object' && !Array.isArray(v)
const finite = (v: unknown): v is number => typeof v === 'number' && Number.isFinite(v)
export const isChallenge = (v: unknown): v is IssuedChallenge => record(v) && typeof v.id === 'string' && (v.kind === 'straight-line' || v.kind === 'hash-recall' && typeof v.hash === 'string' || v.kind === 'image-confusion' && typeof v.prompt === 'string' && typeof v.instruction === 'string' && typeof v.ordered === 'boolean' && Array.isArray(v.tiles) && v.tiles.every(t => record(t) && typeof t.id === 'string' && typeof t.src === 'string')) && finite(v.startedAt) && finite(v.expiresAt)
export const isReceipt = (v: unknown): v is AttemptReceipt => record(v) && v.ok === true && finite(v.attemptId) && typeof v.requestId === 'string' && typeof v.handle === 'string' && typeof v.passed === 'boolean' && typeof v.recordedAt === 'string' && record(v.result) && finite(v.result.score) && record(v.result.meta) && typeof v.result.meta.reason === 'string' && (v.user === null || record(v.user) && finite(v.user.id) && typeof v.user.handle === 'string')
export const isNetwork = (v: unknown): v is NetworkState => record(v) && finite(v.rejections) && finite(v.level) && v.level >= 0 && v.level <= 1 && typeof v.band === 'string' && typeof v.message === 'string' && typeof v.generatedAt === 'string'
export const isPosts = (v: unknown): v is Post[] => Array.isArray(v) && v.every(p => record(p) && finite(p.id) && typeof p.handle === 'string' && typeof p.body === 'string' && finite(p.likes) && finite(p.pinned) && typeof p.created_at === 'string')
export const isComments = (v: unknown): v is Comment[] => Array.isArray(v) && v.every(c => record(c) && finite(c.id) && finite(c.post_id) && typeof c.handle === 'string' && typeof c.body === 'string' && typeof c.created_at === 'string')
export type ProgressResponse = { humanity: number | null; verified: boolean; challenges: Progress[]; detections?: number; terminated?: boolean; transmission: TransmissionRule | null; reply: TransmissionRule | null }
export const isProgress = (v: unknown): v is ProgressResponse => record(v) && typeof v.verified === 'boolean' && (v.detections === undefined || finite(v.detections)) && (v.terminated === undefined || typeof v.terminated === 'boolean') && (v.humanity === null || finite(v.humanity)) && (v.transmission === null || v.transmission === undefined || record(v.transmission) && typeof v.transmission.id === 'string' && typeof v.transmission.instruction === 'string') && (v.reply === null || v.reply === undefined || record(v.reply) && typeof v.reply.id === 'string' && typeof v.reply.instruction === 'string') && Array.isArray(v.challenges) && v.challenges.every(p => record(p) && typeof p.id === 'string' && typeof p.name === 'string' && typeof p.live === 'boolean' && typeof p.passed === 'boolean')
export const isActivity = (v: unknown): v is Activity[] => Array.isArray(v) && v.every(a => record(a) && finite(a.id) && typeof a.kind === 'string' && typeof a.text === 'string' && typeof a.handle === 'string' && typeof a.created_at === 'string')
export const isLeaders = (v: unknown): v is LeaderRow[] => Array.isArray(v) && v.every(a => record(a) && typeof a.handle === 'string' && finite(a.bestTimeMs) && Number.isSafeInteger(a.bestTimeMs) && a.bestTimeMs >= 0)
